=== ealight/FB-Messenger-QuartersBot/src/main/resources/xsd/genericKeyboard.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="generic-keyboard">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="generic-db-item">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="generic-button" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="payload" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="entity"/>
                        <xs:attribute type="xs:byte" name="maxItemsOnPage"/>
                        <xs:attribute type="xs:string" name="itemResponseMethod"/>
                        <xs:attribute type="xs:string" name="repository"/>
                        <xs:attribute type="xs:string" name="repoMethod"/>
                        <xs:attribute type="xs:string" name="methodForTitle"/>
                        <xs:attribute type="xs:string" name="methodForSubtitle"/>
                        <xs:attribute type="xs:string" name="methodForImage"/>
                        <xs:attribute type="xs:string" name="methodForPayload"/>
                        <xs:attribute type="xs:string" name="imageEntity"/>
                        <xs:attribute type="xs:string" name="methodForUrlImage"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="generic-quick-reply">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="quick-reply-button" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="payload" use="optional"/>
                                            <xs:attribute type="xs:boolean" name="pageable" default="true"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="controller"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ealight/FB-Messenger-QuartersBot/src/main/resources/keyboard/generic/allHouses.xml
<?xml version="1.0"?>

<generic-keyboard xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="../../xsd/genericKeyboard.xsd"
                  controller="GenericMenu">

    <generic-db-item entity="House" maxItemsOnPage="3" itemResponseMethod="house"
                     methodForTitle="getName" methodForSubtitle="getDescription"
                     methodForImage="getImages" methodForPayload="getId"
                     imageEntity="HouseImageData" methodForUrlImage="getUrl">

        <generic-button payload="MoreDetails">Подробнее</generic-button>
        <generic-button payload="ToMagazine">Добавить в журнал</generic-button>
        <generic-button payload="Reserve">Забронировать</generic-button>

    </generic-db-item>

    <generic-quick-reply>
        <quick-reply-button payload="Previous">Назад</quick-reply-button>
        <quick-reply-button payload="Page" pageable="true">Страница</quick-reply-button>
        <quick-reply-button payload="Next">Вперед</quick-reply-button>
    </generic-quick-reply>


</generic-keyboard>
