=== ealight/FB-Messenger-QuartersBot/src/main/resources/xsd/persistentKeyboard.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="persistent-keyboard">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persistent-category" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="persistent-link" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="payload" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="title"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="persistent-independent-link" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute type="xs:string" name="payload"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="controller"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ealight/FB-Messenger-QuartersBot/src/main/resources/keyboard/persistent/persistentMenu.xml
<?xml version="1.0"?>

<persistent-keyboard xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../../xsd/persistentKeyboard.xsd"
                 controller="Menu">

    <persistent-category title="Мой профиль">
        <persistent-link payload="ReservedHouses">Мои брони</persistent-link>
        <persistent-link payload="Magazine">Мой журнал</persistent-link>
        <persistent-link payload="Notifications">Уведомления</persistent-link>
    </persistent-category>

    <persistent-category title="Выбрать дом">
        <persistent-link payload="AllHouses">Посмотреть все дома</persistent-link>
        <persistent-link payload="Filters">К фильтрам</persistent-link>
    </persistent-category>

    <persistent-independent-link payload="Start">На главную</persistent-independent-link>

</persistent-keyboard>
